package exportXLS.test;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import exportXLS.entity.UserInfo;
import exportXLS.util.ExcelUtil;



public class ExportExcelTest {

	public static void main(String[] args) {
		List<UserInfo> users = new ArrayList<UserInfo>();
		UserInfo user = new UserInfo();
		user.setAddress("江西省丰城市");
		user.setId(1);
		user.setBrithDate(new Date());
		user.setIdCard("362202********6354");
		user.setQq("101***603");
		user.setSex(0);
		user.setName("戴某某");
		user.setPhone("183****4800");
		users.add(user);
		user = new UserInfo();
		user.setAddress("江西省丰城市");
		user.setId(2);
		user.setBrithDate(new Date());
		user.setIdCard("362202********6354");
		user.setQq("101***603");
		user.setSex(1);
		user.setPhone("186****3897");
		user.setName("王某某");
		users.add(user);
		user = new UserInfo();
		user.setAddress("江西省丰城市");
		user.setId(3);
		user.setBrithDate(new Date());
		user.setIdCard("362202********6354");
		user.setQq("101***603");
		user.setSex(0);
		user.setName("戴某某");
		user.setPhone("18621085177");
		users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(4);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(5);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(6);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(7);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(8);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(9);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(10);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(11);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(12);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(13);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(14);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(15);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(16);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(17);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
        user = new UserInfo();
        user.setAddress("江西省丰城市");
        user.setId(18);
        user.setBrithDate(new Date());
        user.setIdCard("362202********6354");
        user.setQq("101***603");
        user.setSex(1);
        user.setPhone("186****3897");
        user.setName("王某某");
        users.add(user);
		ExcelUtil util = new ExcelUtil();
		try {
			util.exportExcel(users,UserInfo.class);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
